### ISSUE TITLE
ADVGEN error, seems like there is no trajectory generated.

### ISSUE THREAD

**Issue by CesarLiu** [metadriverse/cat#3]
Thanks a lot for the excellent work and Open-sourced code repo.
When running the training process, i got following error. Do you have any idea?
Traceback (most recent call last):
  File "/home/xliu/ws_cat/cat/cat_RLtrain.py", line 233, in <module>
    adv_generator.generate()
  File "/home/xliu/ws_cat/cat/advgen/adv_generator.py", line 423, in generate
    trajs_OV = pred_trajectory[1]
IndexError: index 1 is out of bounds for axis 0 with size 1

**Comment by zhang-linrui** [comment]
Did this happen in the first scene in the training loop, or was there an exception during the training process?

**Comment by CesarLiu** [comment]
Thanks for the quick answer. It was during the training process, I'm using the full validation set. I will try the 500 provided scenarios first
